### ISSUE TITLE
Expose plain HTTP request

### ISSUE THREAD

**Issue by toastal** [jaredramirez/elm-s3#5]
As noted in the [Discourse thread](https://discourse.elm-lang.org/t/upload-files-to-s3/4314/14), due to Elm's `Task` limitation, you cannot get the tracker from a `Task`. Because I want to upload videos, and videos can be quite large, I want the ability to see the progress and cancel.

**Comment by jaredramirez** [comment]
Makes sense! I'll try to get to this in the next week or so
